trossen_rslidar_node:
  ros__parameters:
    # Frame id of packet message and point cloud message (default: rslidar)
    ros_frame_id: rslidar

    # Topic used to send point cloud through ROS/ROS 2 (default: points)
    ros_send_point_cloud_topic: points

    # Meaningful only for Mechanical Lidars, and valid if dense_points = false (default: false)
    ros_send_by_rows: false

    # Whether to discard NAN points (default: false)
    dense_points: true

    # LiDAR type - RS16, RS32, RSBP, RSHELIOS, RSHELIOS_16P, RS128, RS80, RS48, RSP128, RSP80,
    #              RSP48, RSM1, RSM1_JUMBO, RSM2, RSE1 (default: RSHELIOS_16P)
    lidar_type: RSHELIOS_16P

    # Needed in two conditions:
    # If the host receives packets from multiple Lidars via different IP addresses, use this parameter to specify destination IPs of the Lidars.
    # If group_address is set, it should be set, so it will be joined into the multicast group.
    # (default: 0.0.0.0)
    host_address: 0.0.0.0

    # If use multi-cast function, this parameter needs to be set correctly. (default: 0.0.0.0)
    group_address: 0.0.0.0

    # Print the driver configuration parameters (default: false)
    show_driver_config: false

    # The MSOP port to receive LiDAR data or Main data Stream Output Protocol (default: 6699)
    msop_port: 6699

    # DIFOP is an "output-only" protocol to periodically send the LiDAR network and calibration information (default: true)
    wait_for_difop: true

    # The DIFOP port to receive LiDAR network and calibration information  (default: 7788)
    difop_port: 7788

    # The start angle of the point cloud, in the range of 0~360° (default: 0.0)
    start_angle: 0.0

    # The end angle of the point cloud, in the range of 0~360° (default: 360.0)
    end_angle: 360.0

    # The minimum distance of the point cloud in meters (default: 0.2)
    # Min Range of Helios 16P is 0.2m
    min_distance: 0.3

    # The maximum distance of the point cloud in meters (default: 200)
    # Max Range of Helios 16P is 150m
    max_distance: 140.0

    # true to use the lidar clock as the message timestamp, false to use the system clock (default: false)
    use_lidar_clock: false
